[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
    "black.toml",
    "editorconfig.toml",
    "commitizen.toml",
    "pre-commit.toml",
]

["pyproject.toml".tool.isort]
line_length = 80
profile = "black"
float_to_top = true

["pyproject.toml".tool.mypy]
ignore_missing_imports = true
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true

["pyproject.toml".tool.flynt]
transform-concats = true
transform-joins = true
line-length = 120
aggressive = true
