[nitpick]
minimum_version = "0.10.0"

["pyproject.toml".tool.black]
line-length = 80

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/psf/black"

[[".pre-commit-config.yaml".repos.hooks]]
id = "black"
