["pyproject.toml".tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules"
filterwarnings = ["error"]

["pyproject.toml".tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

["pyproject.toml".tool.coverage.run]
branch = true
relative_files = true
